In [2]:
import numpy as np

In [4]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [5]:
a.shape

(6,)

In [6]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [7]:
a2.shape

(1, 6)

In [8]:
a3 = a[:, np.newaxis]
a3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
a3.ndim

2

In [15]:
a.size

6

In [19]:
def get_item(value=None):
    '''
    item을 가져오는 함수를 작성합니다
    '''
    return True

a = get_item()
a2?

Type:        ndarray
String form: [[0 1 2 3 4 5]]
Length:      1
File:        c:\users\test\.conda\envs\hrd\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any 